exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "meeting_management.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'staging', '--branch', 'version-15']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  # - repo: https://github.com/frappe/black
  #   rev: 951ccf4d5bb0d692b457a5ebc4215d755618eb68
  #   hooks:
  #     - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                meeting_management/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                meeting_management/www/website_script.js|
                meeting_management/templates/includes/.*|
                meeting_management/public/js/lib/.*|
                meeting_management/website/doctype/website_theme/website_theme_template.scss
            )$


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
            (?x)^(
                meeting_management/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                meeting_management/www/website_script.js|
                meeting_management/templates/includes/.*|
                meeting_management/public/js/lib/.*
            )$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: ['flake8-bugbear',]

  - repo: local
    hooks:
    - id: check-max-lines
      name: Check Max Lines
      entry: python scripts/check_max_lines.py
      language: python
      types: [python]
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false